dist: trusty
sudo: required
language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop

addons:
  chrome: stable
  firefox: latest
  sauce_connect:
    username: $SAUCE_USERNAME
    access_key: $SAUCE_ACCESS_KEY
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - ./bootstrap.sh
  - pip install --upgrade -r requirements.txt
  - pip install -r test-requirements.txt

script: INTRAVIS=1 ./run-tests.sh
