dist: trusty

language: python
python:
  - "3.6"

addons:
  chrome: stable

env:
  - CHROME="google-chrome-stable"

before_install:
  - ./bootstrap.sh

install:
  - apt-get -qq update
  - apt install chromedriver
  - pip install -r requirements.txt

script: 
  - pytest -v -s
