sudo: required

language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop

addons:
  chrome: stable

env:
  - CHROME="google-chrome-stable"

before_install:
  - ./bootstrap.sh

install:
  - sudo apt-get -qq update
  - sudo apt install chromedriver
  - pip install -r requirements.txt

script: 
  - pytest -v -s
