dist: trusty
sudo: true
language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - ./bootstrap.sh
  - pip install --upgrade -r requirements.txt

script: INTRAVIS=1 ./run-tests.sh
