sudo: required

language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop

addons:
  chrome: stable

env:
  - CHROME="google-chrome-stable"

before_install:
  - sudo apt-get -qq update
  - sudo apt install libgconf-2-4
  - wget -nc -O - https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip | gunzip - > /tmp/chromedriver
  - chmod +x /tmp/chromedriver
  - mv /tmp/chromedriver /usr/local/bin/chromedriver

install:
  - ./bootstrap.sh
  - pip install -r requirements.txt

script: 
  - pytest -v -s
