dist: trusty
sudo: false
language: python
python:
  - "3.6"

branches:
  only:
  - master
  - develop

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

install:
  - ./bootstrap.sh
  - pip install -r requirements.txt

script: ./run-tests.sh
